### ISSUE TITLE
Sample Google cloud provider config

### ISSUE THREAD

**Issue by coolpalani** [alexbrand/ket-on-azure#3]
Hello @alexbrand 

I am trying to configure Kubernetes in Google Cloud platform using kismatic.
Could you share sample google-cloud-provider.conf.sample file

Thanks in advance.

**Comment by alexbrand** [comment]
Hey @coolpalani,

I am not familiar with GCP enough, and currently busy with other projects. You might want to reach out to @dkoshkin via the official kismatic repo (https://github.com/apprenda/kismatic). The kismatic team will most likely be able to help.
